# .readthedocs.yaml
# Read the Docs configuration file
# See httpsdocs.readthedocs.ioenstableconfig-filev2.html for details

# Required
version 2

# Set the version of Python and other tools you might need
#build
#  os ubuntu-20.04
#  tools
#    python 3.7

mkdocs
  configuration mkdocs.yml

formats: all

# Optionally declare the Python requirements required to build your docs
python
  version: 3.7
   install
   - requirements docsrequirements.txt