# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

mkdocs:
  configuration: mkdocs.yml

formats: all

python:
  version: 3.7
  install:
<<<<<<< HEAD
    - requirements: Docs/requirements.txt
=======
    - requirements: Docs/requirements.txt
>>>>>>> 640b6945e128c21bc11fd3fcae69fd11332533e2
